FROM python:3.9.1-slim

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN apt-get update \
    && apt-get install gcc -y \
    && apt-get clean

RUN pip install -r /app/requirements.txt \
    && rm -rf /root/.cache/pip

RUN apt-get install libpq-dev -y \
    && pip install psycopg2

COPY . /app/